<?php

session_start();
ini_set('max_execution_time', 0); // 0 = Unlimited
$headerTitle = 'APPLICATION FOR MERIT AWARD / SCHOLARSHIP ';
include_once 'common/logs.php';
include_once 'common/db.php';
include_once 'common/functions.php';

$arr = array(
    array(
        "id" => 30,
        "App.No." => "VBM000001",
        "Name of the Student" => "Kande Santhosh Kumar",
        "Medal" => "Gold",
        "Medal Category" => "CA Final - Group I",
        "" => "CA Sanka Venu Gopal",
        "" => 9133486799,
        "number" => 9441565721,
        "name" => "BPK",
        "emailid" => "santosh55199755@gmail.com"),
    array(
        "id" => 32,
        "App.No." => "VBM000002",
        "Name of the Student" => "Kothamasu Murali Krishna",
        "Medal" => "Gold",
        "Medal Category" => "CA Final - Group II",
        "" => "CA Gelli Naresh Chandra",
        "" => 8686026977,
        "number" => 8919264467,
        "name" => "KRB",
        "emailid" => "manikanta.kothamasu1@gmail.com"),
    array(
        "id" => 28,
        "App.No." => "VBM000013",
        "Name of the Student" => "Channa Venkata Sai Akhil",
        "Medal" => "Gold",
        "Medal Category" => "CA Final - Both Groups ",
        "" => "Smt. A Surekha",
        "" => 8332876540,
        "number" => 9849436833,
        "name" => "BPK",
        "emailid" => "channaakhil@gmail.com"),
    array(
        "id" => 33,
        "App.No." => "VBM000021",
        "Name of the Student" => "Saka Bhanu Teja",
        "Medal" => "Gold",
        "Medal Category" => "CA Inter - Both Groups",
        "" => "CA K V Prasad",
        "" => 7995476498,
        "number" => 9866153176,
        "name" => "KRB",
        "emailid" => "bhanutej563@gmail.com"),
    array(
        "id" => 38,
        "App.No." => "VBM000062",
        "Name of the Student" => "Kukutla Tarun",
        "Medal" => "Gold",
        "Medal Category" => "CA Inter - Group II",
        "" => "Er J.Subbaraya Setty & CA J R P Guptha",
        "" => 7893441283,
        "number" => 9989785909,
        "name" => "KRB",
        "emailid" => "kukutlatarun@gmail.com"),
    array(
        "id" => 22,
        "App.No." => "VBM000107",
        "Name of the Student" => "Katakam Madhurima",
        "Medal" => "Gold",
        "Medal Category" => "Inter - CEC",
        "" => "CA  C.V.M. Srinivas",
        "" => 7286804411,
        "number" => 9704734275,
        "name" => "BPK",
        "emailid" => "krmallesham@gmail.com"),
    array(
        "id" => 16,
        "App.No." => "VBM000195",
        "Name of the Student" => "Innamuri Gnana Lakshmi Chandini",
        "Medal" => "Silver",
        "Medal Category" => "Inter - MPC",
        "" => "Dr Balabadruni Kameswara Rao",
        "" => 9398798244,
        "number" => 9948889789,
        "name" => "BPK",
        "emailid" => "innamurichandini@gmail.com"),
    array(
        "id" => 17,
        "App.No." => "VBM000195",
        "Name of the Student" => "Innamuri Gnana Lakshmi Chandini",
        "Medal" => "Gold",
        "Medal Category" => "Inter - Maths",
        "" => "CA S Narayana Murthy",
        "" => 9398798244,
        "number" => 9948889789,
        "name" => "BPK",
        "emailid" => "innamurichandini@gmail.com"),
    array(
        "id" => 3,
        "App.No." => "VBM000220",
        "Name of the Student" => "Challa Sri Pooja Chandra",
        "Medal" => "Silver",
        "Medal Category" => "SSC",
        "" => "Er  M. Rajeswara Gupta",
        "" => 9849797965,
        "number" => 9849797965,
        "name" => "KLK",
        "emailid" => "chandra_7965@yahoo.co.in"),
    array(
        "id" => 7,
        "App.No." => "VBM000220",
        "Name of the Student" => "Challa Sri Pooja Chandra",
        "Medal" => "Gold",
        "Medal Category" => "SSC - Maths",
        "" => "Vyspro - India",
        "" => 9849797965,
        "number" => 9849797965,
        "name" => "KLK",
        "emailid" => "chandra_7965@yahoo.co.in"),
    array(
        "id" => 36,
        "App.No." => "VBM000235",
        "Name of the Student" => "Dachapalli Naveen",
        "Medal" => "Gold",
        "Medal Category" => "CA Inter - Group I",
        "" => "CA Beldi Sridhar",
        "" => 7842113800,
        "number" => 8639928605,
        "name" => "KRB",
        "emailid" => "Naveengupta99890@gmail.com"),
    array(
        "id" => 21,
        "App.No." => "VBM000255",
        "Name of the Student" => "Kotha Sai Tripura",
        "Medal" => "Silver",
        "Medal Category" => "Inter - BiPC",
        "" => "Sri B. Praveen Kumar",
        "" => 9381171832,
        "number" => 9393245374,
        "name" => "BPK",
        "emailid" => "Saitripura2018@gmail.com"),
    array(
        "id" => 27,
        "App.No." => "VBM000257",
        "Name of the Student" => "Mucharla Naga Sai Sampath Kumar",
        "Medal" => "Silver",
        "Medal Category" => "CA CPT",
        "" => "Vyspro - India",
        "" => 9247460445,
        "number" => 9246771725,
        "name" => "BPK",
        "emailid" => "sampu2003@gmail.com"),
    array(
        "id" => 23,
        "App.No." => "VBM000259",
        "Name of the Student" => "Mucharla Naga Sai Sampath Kumar",
        "Medal" => "Gold",
        "Medal Category" => "Inter - MEC",
        "" => "CA Sathuluri Prakash",
        "" => 9247460445,
        "number" => 9246771725,
        "name" => "BPK",
        "emailid" => "sampu2003@gmail.com"),
    array(
        "id" => 19,
        "App.No." => "VBM000260",
        "Name of the Student" => "Dasa Sampath",
        "Medal" => "Gold",
        "Medal Category" => "Inter - Maths",
        "" => "CA S V R Visweswara Rao",
        "" => 6302006002,
        "number" => 9866612715,
        "name" => "BPK",
        "emailid" => "sampathdasa01@gmail.com"),
    array(
        "id" => 41,
        "App.No." => "VBM000268",
        "Name of the Student" => "Busetty Mahesh",
        "Medal" => "Gold",
        "Medal Category" => "CMA Inter - Both Groups",
        "" => "Sri. Jallipally Sekhar Rao",
        "" => 9514326461,
        "number" => 9941178916,
        "name" => "KRB",
        "emailid" => "damodaramb@rediffmail.com"),
    array(
        "id" => 37,
        "App.No." => "VBM000270",
        "Name of the Student" => "Busetty Mahesh",
        "Medal" => "Silver",
        "Medal Category" => "CA Inter - Group I",
        "" => "Sri Desu Srinivas",
        "" => 9514326461,
        "number" => 9941178916,
        "name" => "KRB",
        "emailid" => "damodaramb@rediffmail.com"),
    array(
        "id" => 45,
        "App.No." => "VBM000281",
        "Name of the Student" => "Chinnam Sanghavi",
        "Medal" => "Gold",
        "Medal Category" => "MBA",
        "" => "Er Gajjala Yoganand",
        "" => 8106030979,
        "number" => 9542711998,
        "name" => "KRB",
        "emailid" => "chinnamsanghavi@gmail.com"),
    array(
        "id" => 25,
        "App.No." => "VBM000285",
        "Name of the Student" => "Arvapally Sreeja",
        "Medal" => "Silver",
        "Medal Category" => "B Com",
        "" => "Sri J Mahaveer Prasad Singhania",
        "" => 9441968756,
        "number" => 9032815293,
        "name" => "BPK",
        "emailid" => "arvapally.sreejagupta12345@gmail.com"),
    array(
        "id" => 18,
        "App.No." => "VBM000288",
        "Name of the Student" => "Masetty Venkata Sai Mahesh",
        "Medal" => "Gold",
        "Medal Category" => "Inter - Maths",
        "" => "Sri K.Koteswara Rao",
        "" => 7981118276,
        "number" => 9441213285,
        "name" => "BPK",
        "emailid" => "m.venkatasaimahesh123@gmail.com"),
    array(
        "id" => 26,
        "App.No." => "VBM000305",
        "Name of the Student" => "Pabbisetty Jai Mithra",
        "Medal" => "Gold",
        "Medal Category" => "CA CPT",
        "" => "CA S.Sambasiva Rao",
        "" => 6304753596,
        "number" => 9963841369,
        "name" => "BPK",
        "emailid" => "jaimithra.pabbisetty108@gmail.com"),
    array(
        "id" => 15,
        "App.No." => "VBM000314",
        "Name of the Student" => "Suggala Pragnasri",
        "Medal" => "Gold",
        "Medal Category" => "Inter - MPC",
        "" => "Dr Balabadruni Kameswara Rao",
        "" => 9347668365,
        "number" => 9440630478,
        "name" => "KLK",
        "emailid" => "Suggala.pragnasri@gmail.com"),
    array(
        "id" => 24,
        "App.No." => "VBM000338",
        "Name of the Student" => "Tadikamalla Sai Hemanth",
        "Medal" => "Silver",
        "Medal Category" => "Inter - MEC",
        "" => "Er. Gollapudi Mahesh Kumar",
        "" => 7095355861,
        "number" => 9346741626,
        "name" => "BPK",
        "emailid" => "hemu1207.t@gmail.com"),
    array(
        "id" => 4,
        "App.No." => "VBM000342",
        "Name of the Student" => "Suda Mohan Bharath Kumar",
        "Medal" => "Silver",
        "Medal Category" => "SSC",
        "" => "Vyspro - India",
        "" => 8498841301,
        "number" => 9063056156,
        "name" => "KLK",
        "emailid" => "lakshmisuda@gmail.com"),
    array(
        "id" => 8,
        "App.No." => "VBM000342",
        "Name of the Student" => "Suda Mohan Bharath Kumar",
        "Medal" => "Gold",
        "Medal Category" => "SSC - Maths",
        "" => "Vyspro - India",
        "" => 8498841301,
        "number" => 9063056156,
        "name" => "KLK",
        "emailid" => "lakshmisuda@gmail.com"),
    array(
        "id" => 34,
        "App.No." => "VBM000383",
        "Name of the Student" => "Thommandru Arun Sumanth",
        "Medal" => "Silver",
        "Medal Category" => "CA Inter - Both Groups",
        "" => "CA Gelli Naresh Chandra",
        "" => 9908336718,
        "number" => 6305778533,
        "name" => "KRB",
        "emailid" => "arunsumanth2001@gmail.com"),
    array(
        "id" => 35,
        "App.No." => "VBM000383",
        "Name of the Student" => "Thommandru Arun Sumanth",
        "Medal" => "Gold",
        "Medal Category" => "CA Inter - Law",
        "" => "CA C V S Balachandra Rao",
        "" => 9908336718,
        "number" => 6305778533,
        "name" => "KRB",
        "emailid" => "arunsumanth2001@gmail.com"),
    array(
        "id" => 10,
        "App.No." => "VBM000388",
        "Name of the Student" => "Munaga Dinesh Kumar",
        "Medal" => "Gold",
        "Medal Category" => "SSC - Maths",
        "" => "Vyspro - India",
        "" => 8247306728,
        "number" => 9603569305,
        "name" => "KLK",
        "emailid" => "Muanagadineshkumar123@gmail.vom"),
    array(
        "id" => 12,
        "App.No." => "VBM000399",
        "Name of the Student" => "Kakaraparthi Tarak Sai",
        "Medal" => "Gold",
        "Medal Category" => "SSC - Maths",
        "" => "Vyspro - India",
        "" => 9553290188,
        "number" => 9182588459,
        "name" => "KLK",
        "emailid" => "parameswararaok67156@gmail.com"),
    array(
        "id" => 42,
        "App.No." => "VBM000427",
        "Name of the Student" => "Boggarapu Sai Ram",
        "Medal" => "Silver",
        "Medal Category" => "CMA Inter - Both Groups",
        "" => "CMA Final",
        "" => 7416298118,
        "number" => 9440234593,
        "name" => "KRB",
        "emailid" => "sairam0780@gmail.com"),
    array(
        "id" => 29,
        "App.No." => "VBM000431",
        "Name of the Student" => "Inavolu Sai Pavan",
        "Medal" => "Silver",
        "Medal Category" => "CA Final - Both ",
        "" => "Sri Vadakattu J P Gupta",
        "" => 9959632242,
        "number" => 9704896652,
        "name" => "BPK",
        "emailid" => "inavolupavan.123@gmail.com"),
    array(
        "id" => 11,
        "App.No." => "VBM000443",
        "Name of the Student" => "Peruri Chandana Lakshmi",
        "Medal" => "Gold",
        "Medal Category" => "SSC - Maths",
        "" => "Vyspro - India",
        "" => 8367590490,
        "number" => 8367590490,
        "name" => "KLK",
        "emailid" => "2706murty@gmail.com"),
    array(
        "id" => 1,
        "App.No." => "VBM000445",
        "Name of the Student" => "Patchigolla Moulika",
        "Medal" => "Gold",
        "Medal Category" => "SSC",
        "" => "CA N.Venkateswara Rao",
        "" => 9030201956,
        "number" => 9030544229,
        "name" => "KLK",
        "emailid" => "vishalapatchigolla.1985@gmail.com"),
    array(
        "id" => 5,
        "App.No." => "VBM000445",
        "Name of the Student" => "Patchigolla Moulika",
        "Medal" => "Gold",
        "Medal Category" => "SSC - Maths",
        "" => "CA Chaluvadi Srinivasa Rao",
        "" => 9030201956,
        "number" => 9030544229,
        "name" => "KLK",
        "emailid" => "vishalapatchigolla.1985@gmail.com"),
    array(
        "id" => 44,
        "App.No." => "VBM000447",
        "Name of the Student" => "Vandanapu Lasyapriya",
        "Medal" => "Silver",
        "Medal Category" => "Engineering",
        "" => "Er Rachuri Srinivasa Rao",
        "" => 9490916977,
        "number" => 9440389577,
        "name" => "KRB",
        "emailid" => "lasyapriya.v1997@gmail.com"),
    array(
        "id" => 46,
        "App.No." => "VBM000471",
        "Name of the Student" => "Kolipaka Manvitha",
        "Medal" => "Gold",
        "Medal Category" => "MBBS",
        "" => "Sri Manepalli Suryamanikyam",
        "" => 9603581296,
        "number" => 7013584389,
        "name" => "KRB",
        "emailid" => "kolipakamanvitha@gmail.com"),
    array(
        "id" => 13,
        "App.No." => "VBM000472",
        "Name of the Student" => "Nama Akshitha",
        "Medal" => "Gold",
        "Medal Category" => "SSC - Maths",
        "" => "Vyspro - India",
        "" => 9441346038,
        "number" => 9912168850,
        "name" => "KLK",
        "emailid" => "anandkumarnama9@gmail.com"),
    array(
        "id" => 39,
        "App.No." => "VBM000507",
        "Name of the Student" => "Gunda Karthik",
        "Medal" => "Silver",
        "Medal Category" => "CA Inter - Group II",
        "" => "CA Final Group-II",
        "" => 7396646515,
        "number" => 9550837520,
        "name" => "KRB",
        "emailid" => "karthikgunda22@gmail.com"),
    array(
        "id" => 2,
        "App.No." => "VBM000529",
        "Name of the Student" => "Kollipara Ramya Sri Abhitha",
        "Medal" => "Gold",
        "Medal Category" => "SSC",
        "" => "Vyspro - India",
        "" => 9989259484,
        "number" => 9989259484,
        "name" => "KLK",
        "emailid" => "rameshklpr@gmail.com"),
    array(
        "id" => 6,
        "App.No." => "VBM000529",
        "Name of the Student" => "Kollipara Ramya Sri Abhitha",
        "Medal" => "Gold",
        "Medal Category" => "SSC - Maths",
        "" => "Vyspro - India",
        "" => 9989259484,
        "number" => 9989259484,
        "name" => "KLK",
        "emailid" => "rameshklpr@gmail.com"),
    array(
        "id" => 9,
        "App.No." => "VBM000532",
        "Name of the Student" => "Kollipara Chaitanya Abhishikth",
        "Medal" => "Gold",
        "Medal Category" => "SSC - Maths",
        "" => "Vyspro - India",
        "" => 9989259484,
        "number" => 9989259484,
        "name" => "KLK",
        "emailid" => "rameshklpr@gmail.com"),
    array(
        "id" => 43,
        "App.No." => "VBM000536",
        "Name of the Student" => "Kolla G V S L Priyanka",
        "Medal" => "Gold",
        "Medal Category" => "Engineering",
        "" => "Er Rachuri Srinivasa Rao",
        "" => 8977103203,
        "number" => 9966492194,
        "name" => "KRB",
        "emailid" => "priyankakolla16@gmail.com"),
    array(
        "id" => 31,
        "App.No." => "VBM000547",
        "Name of the Student" => "Morishetty Srikanth",
        "Medal" => "Silver",
        "Medal Category" => "CA Final - Group I",
        "" => "CA Soma Vidya Sagar",
        "" => 8106064040,
        "number" => 9441912331,
        "name" => "KRB",
        "emailid" => "morishettysrikanth@gmail.com"),
    array(
        "id" => 40,
        "App.No." => "VBM000554",
        "Name of the Student" => "Kurapati Sasanka Veera Venkatesh",
        "Medal" => "Gold",
        "Medal Category" => "CMA Final",
        "" => "CMA D L S Sresti",
        "" => 9542356063,
        "number" => 9989827935,
        "name" => "KRB",
        "emailid" => "kurapati.s.v.venkatesh@gmail.com"),
    array(
        "id" => 20,
        "App.No." => "VBM000580",
        "Name of the Student" => "Kodithala Priyanka ",
        "Medal" => "Gold",
        "Medal Category" => "Inter - BiPC",
        "" => "CA S V R Visweswara Rao",
        "" => 8886934333,
        "number" => 8886934333,
        "name" => "BPK",
        "emailid" => "kedar_eshwar2002@yahoo.com"),
    array(
        "id" => 14,
        "Name of the Student" => "Samayamanthula Pruthvi Chaithanya",
        "Medal" => "Gold",
        "Medal Category" => "SSC - Maths",
        "" => "Vyspro - India",
        "" => 9490261789,
        "number" => 9246198546,
        "name" => "KLK")
);
//echo "<pre>";
//Print_r($arr);

$i = 0;
//$emailis = array('bpkleo2002@gmail.com', 'praveenkumar.bolisetty@gmail.com','rameshklpr@gmail.com','leelakrishna.ca@gmail.com','gururaj.g@gmkco.com');
//$emailis = array('bpkleo2002@gmail.com', 'bpkleo2002@gmail.com', 'bpkleo2002@gmail.com', 'bpkleo2002@gmail.com', 'bpkleo2002@gmail.com');
foreach ($arr as $student) {
//    $toUser = $emailis[$i];
    $toUser = $student['emailid'];
    $subject = "CONGRATULATIONS Dear " . $student['Name of the Student'] . " from Vyspro-India : Vidhya Bharathi 2019 ";
//    echo "<br />";
//    print_r($student['Name of the Donor']);
//exit;
    $message = file_get_contents('thanksemai.php');
    $message = str_replace('%%%number%%%', $student['App.No.'], $message);
    $message = str_replace('%%%studentname%%%', $student['Name of the Student'], $message);
    $message = str_replace('%%%medaltype%%%', $student['Medal'], $message);
    $message = str_replace('%%%study%%%', $student['Medal Category'], $message);
//echo $message;
//    echo "<br /><br /><br />---------------------------------------------------------------<br /><br />";
    $statusemail = sendGmail($toUser, $subject, $message);
    print_r($statusemail);
//    $i++;
//    if ($i > 4) {
//        break;
//    }
}
